name: Test pyglider
on: [push, pull_request]

defaults:
  run:
    shell: bash -el {0}

jobs:
  test-gliders:
    name: pyglider (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: mamba setup enviroment
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          environment-name: test-env
          environment-file: tests/environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Conda info
        run: |
          conda info
          conda list
      - name: install pyglider source
        run: |
          which pip
          pip install -e .
      - name: Process seaexplorer
        run: |
          which python
          cd tests/example-data/example-seaexplorer
          make clean-all
          python process_deploymentRealTime.py
      - name: Process slocum
        run: |
          which python
          cd tests/example-data/example-slocum
          make clean-all
          python process_deploymentRealTime.py
      - name: Process seaexplorer-legato-flntu-arod-ad2cp
        run: |
          which python
          cd tests/example-data/example-seaexplorer-legato-flntu-arod-ad2cp
          make clean-all
          python process_deploymentRealTime.py
      - name: Run tests
        run: |
          which python
          pytest --cov --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
